stages:
  - build
  - linters
  - test
  - deploy

variables:
  DOCKER_IMAGE: $DOCKER_USERNAME/fastapi-blog:$CI_COMMIT_SHORT_SHA

# Общие правила для большинства jobs
.common_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod"'
    - if: '$CI_COMMIT_BRANCH =~ /^feat\/.*/'
    - if: '$CI_COMMIT_BRANCH =~ /^fix\/.*/'
    - if: '$CI_MERGE_REQUEST_ID'

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod"'
    - if: '$CI_MERGE_REQUEST_ID'
    - if: '$CI_COMMIT_BRANCH =~ /^feat\/.*/ || $CI_COMMIT_BRANCH =~ /^fix\/.*/'
      when: manual

linters:
  stage: linters
  image: $DOCKER_IMAGE
  script:
    - ruff check .
  rules:
    - !reference [.common_rules, rules]

test:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - pytest --maxfail=1 --disable-warnings -q
  rules:
    - !reference [.common_rules, rules]

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_HOST "
        cd ~/fastapi-app/fastapi-blog &&
        git pull &&
        export DOCKER_IMAGE=$DOCKER_IMAGE &&
        export DATABASE_URL=$DATABASE_URL &&
        docker-compose -f docker-compose.prod.yml pull &&
        docker-compose -f docker-compose.prod.yml down &&
        docker-compose -f docker-compose.prod.yml up -d
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual