version: "3.8"

services:
  web:
    build: .
    restart: always
    env_file:
      - ${ENV_FILE:-.env.local}
    expose:
      - "8000" 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" 
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web