version: "3.8"

services:
  web:
    image: $DOCKER_IMAGE
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
